[2023-01-23T20:52:03.111+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_extraction_and_loading_18.extract_data manual__2023-01-23T20:52:00.791741+00:00 [queued]>
[2023-01-23T20:52:03.122+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_extraction_and_loading_18.extract_data manual__2023-01-23T20:52:00.791741+00:00 [queued]>
[2023-01-23T20:52:03.123+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T20:52:03.124+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-01-23T20:52:03.125+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T20:52:03.133+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract_data> on 2023-01-23 20:52:00.791741+00:00
[2023-01-23T20:52:03.153+0000] {standard_task_runner.py:55} INFO - Started process 12700 to run task
[2023-01-23T20:52:03.168+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_and_loading_18', 'extract_data', 'manual__2023-01-23T20:52:00.791741+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp4jq7qjlm']
[2023-01-23T20:52:03.172+0000] {standard_task_runner.py:83} INFO - Job 152: Subtask extract_data
[2023-01-23T20:52:03.199+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-23T20:52:03.261+0000] {task_command.py:388} INFO - Running <TaskInstance: data_extraction_and_loading_18.extract_data manual__2023-01-23T20:52:00.791741+00:00 [running]> on host 1b696c32fad4
[2023-01-23T20:52:03.316+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abdessamad
AIRFLOW_CTX_DAG_ID=data_extraction_and_loading_18
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T20:52:00.791741+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-23T20:52:00.791741+00:00
[2023-01-23T20:52:41.467+0000] {logging_mixin.py:137} INFO - Error
[2023-01-23T20:52:41.833+0000] {logging_mixin.py:137} INFO - Error
[2023-01-23T20:52:42.006+0000] {logging_mixin.py:137} INFO - Error
[2023-01-23T20:52:42.117+0000] {logging_mixin.py:137} INFO - Error
[2023-01-23T20:52:42.119+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 17, in extract_data
    data_extractor.store_data_in_mongo(data, collection_name=temp_collection_name)
  File "/opt/airflow/dags/helpers.py", line 118, in store_data_in_mongo
    collection = db[collection_name]
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/database.py", line 237, in __getitem__
    return Collection(self, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/collection.py", line 212, in __init__
    raise TypeError("name must be an instance of str")
TypeError: name must be an instance of str
[2023-01-23T20:52:42.146+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_and_loading_18, task_id=extract_data, execution_date=20230123T205200, start_date=20230123T205203, end_date=20230123T205242
[2023-01-23T20:52:42.167+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 152 for task extract_data (name must be an instance of str; 12700)
[2023-01-23T20:52:42.213+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-23T20:52:42.242+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
