[2023-01-29T19:42:43.579+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline_1.extract_data manual__2023-01-29T19:42:42.344909+00:00 [queued]>
[2023-01-29T19:42:43.597+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline_1.extract_data manual__2023-01-29T19:42:42.344909+00:00 [queued]>
[2023-01-29T19:42:43.597+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T19:42:43.598+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-01-29T19:42:43.598+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T19:42:43.642+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract_data> on 2023-01-29 19:42:42.344909+00:00
[2023-01-29T19:42:43.654+0000] {standard_task_runner.py:55} INFO - Started process 236 to run task
[2023-01-29T19:42:43.662+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_1', 'extract_data', 'manual__2023-01-29T19:42:42.344909+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp4c1qyd0z']
[2023-01-29T19:42:43.665+0000] {standard_task_runner.py:83} INFO - Job 2: Subtask extract_data
[2023-01-29T19:42:43.710+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-29T19:42:43.771+0000] {task_command.py:388} INFO - Running <TaskInstance: data_pipeline_1.extract_data manual__2023-01-29T19:42:42.344909+00:00 [running]> on host 84fb6dd1372f
[2023-01-29T19:42:43.882+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abdessamad
AIRFLOW_CTX_DAG_ID=data_pipeline_1
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T19:42:42.344909+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-29T19:42:42.344909+00:00
[2023-01-29T19:43:12.443+0000] {logging_mixin.py:137} INFO - Error
[2023-01-29T19:43:12.565+0000] {logging_mixin.py:137} INFO - Error
[2023-01-29T19:43:12.643+0000] {logging_mixin.py:137} INFO - Error
[2023-01-29T19:43:12.688+0000] {logging_mixin.py:137} INFO - Error
[2023-01-29T19:43:12.727+0000] {logging_mixin.py:137} INFO - Error
[2023-01-29T19:43:13.259+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-29T19:43:13.282+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=data_pipeline_1, task_id=extract_data, execution_date=20230129T194242, start_date=20230129T194243, end_date=20230129T194313
[2023-01-29T19:43:13.357+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-29T19:43:13.410+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
